import type { CustomScenarioConfig } from "./types"

export const SCENARIO_TEMPLATES: Record<string, CustomScenarioConfig[]> = {
  "ancient-mystery": [
    {
      id: "template-ancient-mystery-1",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["ancient-mystery"],
      region: "Gondor",
      location: "The Archives of Minas Tirith",
      questHook: "Ancient scrolls whisper your name - someone is seeking you through the ages",
      tones: ["mysterious", "dark"],
      combatFrequency: 2,
      companionPreference: "solo",
      uniqueElement: "A map that changes each dawn",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Ancient mystery in Gondor",
      },
    },
    {
      id: "template-ancient-mystery-2",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["ancient-mystery"],
      region: "Moria",
      location: "The Chamber of Mazarbul",
      questHook: "A forgotten dwarven artifact has been uncovered in the depths",
      tones: ["mysterious", "melancholic"],
      combatFrequency: 3,
      companionPreference: "single-ally",
      uniqueElement: "Shadows that remember the past",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Ancient mystery in Moria",
      },
    },
    {
      id: "template-ancient-mystery-3",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["ancient-mystery"],
      region: "Rivendell",
      location: "The Hall of Fire",
      questHook: "Elven scholars seek your help deciphering a prophecy",
      tones: ["mysterious", "hopeful"],
      combatFrequency: 1,
      companionPreference: "solo",
      uniqueElement: "Dreams that reveal ancient truths",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Ancient mystery in Rivendell",
      },
    },
  ],
  "desperate-defense": [
    {
      id: "template-desperate-defense-1",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["desperate-defense"],
      region: "Rohan",
      location: "Helm's Deep",
      questHook: "Orcs mass at the gates - the fortress must hold until dawn",
      tones: ["epic", "desperate"],
      combatFrequency: 5,
      companionPreference: "small-party",
      uniqueElement: "A horn that summons aid from afar",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Desperate defense at Helm's Deep",
      },
    },
    {
      id: "template-desperate-defense-2",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["desperate-defense"],
      region: "Gondor",
      location: "Osgiliath",
      questHook: "Hold the river crossing against the forces of Mordor",
      tones: ["desperate", "dark"],
      combatFrequency: 5,
      companionPreference: "large-fellowship",
      uniqueElement: "Ancient defenses that still respond to command",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Desperate defense at Osgiliath",
      },
    },
    {
      id: "template-desperate-defense-3",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["desperate-defense"],
      region: "Shire",
      location: "The Bounds of the Shire",
      questHook: "Protect the peaceful lands from an unexpected threat",
      tones: ["desperate", "personal"],
      combatFrequency: 3,
      companionPreference: "single-ally",
      uniqueElement: "The courage of the small folk",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Desperate defense in the Shire",
      },
    },
  ],
  "noble-quest": [
    {
      id: "template-noble-quest-1",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["noble-quest"],
      region: "Rohan",
      location: "Edoras",
      questHook: "The king calls upon you to undertake a mission of great importance",
      tones: ["epic", "hopeful"],
      combatFrequency: 3,
      companionPreference: "small-party",
      uniqueElement: "A blade reforged from ancient steel",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Noble quest in Rohan",
      },
    },
    {
      id: "template-noble-quest-2",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["noble-quest"],
      region: "Gondor",
      location: "Minas Tirith",
      questHook: "Retrieve a lost heirloom to restore hope to the people",
      tones: ["hopeful", "epic"],
      combatFrequency: 2,
      companionPreference: "single-ally",
      uniqueElement: "The white tree's last seedling",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Noble quest in Gondor",
      },
    },
    {
      id: "template-noble-quest-3",
      generatedAt: Date.now(),
      creationMethod: "vibe-first",
      vibes: ["noble-quest"],
      region: "Rivendell",
      location: "The Council Chamber",
      questHook: "Join a fellowship to accomplish what no single hero could",
      tones: ["epic", "hopeful"],
      combatFrequency: 3,
      companionPreference: "large-fellowship",
      uniqueElement: "Bonds forged between unlikely allies",
      aiContext: {
        characterContext: "Generated from character",
        userPrompt: "Noble quest from Rivendell",
      },
    },
  ],
}

export function getFallbackScenarios(vibes: string[]): CustomScenarioConfig[] {
  const primaryVibe = vibes[0] || "noble-quest"
  const templates = SCENARIO_TEMPLATES[primaryVibe] || SCENARIO_TEMPLATES["noble-quest"]
  return templates
}
